### ISSUE TITLE
Task causes flicker in VSTS UI 

### ISSUE THREAD

**Issue by mkosieradzki** [chamindac/vsts.release.task.download-artifacts#2]
Task causes flicker in VSTS UI when opening deployment log when deployment is in progress.

Probably reason for flickering is because there is no appriopriate Write-Host command, but that's only a guess.

https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md

My bet there is ##vso[task.complete] missing.

I use build agent v2.0

**Comment by chamindac** [comment]
Fixed with @dhoare12 adding the complete to task.
