### ISSUE TITLE
Multiple artifacts

### ISSUE THREAD

**Issue by zivillian** [chamindac/vsts.release.task.download-artifacts#4]
In TFS 2017 it is possible to link multiple builds to a single release definition. I was not able to find a way to filter the Artifacts per Artifact Source.
Imagine the following builds and artifacts:

- Build01
  - Test
  - Binary
  - Script
- Build02
  - Test
  - Binary
  - Script
  - Ressources

I want to release with a single definition using 4 environments, each needing distinct artifacts: 
#### Prepare
- Build01\Script
- Build02\Script
#### Publish internal
- Build01\Binary
#### Publish external
- Build02\Binary
- Build02\Ressources
#### Integration Test
- Build01\Test
- Build02\Test

Each of the Artifact will be around 50MB, so filtering reduces the download size by an order of magnitude when there are more than two Builds.

If this is already supported, please let me know how I should configure the filter.

**Comment by kickinattech** [comment]
Hello

Is there any news on this?

As just downloaded the extension and as the comment above we have several artifacts linked to a single release template. It is meant that I had to remove extension until it is supported.

Which is a shame as would have been useful to use this extension.

From

Russell

**Comment by gregpakes** [comment]
This is how I expected the extension to work.  I have a release that is already linked to 4 artifact sources.  I wanted to be able to filter these, but it doesn't seem to work like that, unless I'm missing something?

**Comment by chamindac** [comment]
@gregpakes @russelldyas @zivillian Aplogies for the delay in updating the extension to support multiple artifacts. I have enabled a new task to the extension **Download Artifacts (New)** which is capable of downloading from multiple linked builds. works fine with the single build as well with a slight modification to the paths provided. Now it is supporting * or **ArtifactSourceAlias\Artifactname** format. You can specify artifacts linked from other team projects as well.

Let me know if it works for you.

**Example Build Artifact Names field values**
*

MVC5.Rel\Drop\

MVC5.Rel\Drop\MVS5WebApp\Views;X1.MVC5.Rel\Drop\MVCWebApp_Package;X1.MVC5.Rel\Drop\MVCWebApp\bin\MVCWebApp.dll

DB.Rel\Drop;MVC5.Rel\Drop

(c953e4820b62948d8bf68f5e4b7831ab352e6888)

**Comment by gregpakes** [comment]
I'm not sure I'm following this.

My thought process is as follows:

I have a release which is linked to 4 different builds (linked artifacts) as follows:

Source Alias | Type
------------- | ----------
Build1 | Build
Build2 | Build
Build3 | Build
Build4 | Build

I was expecting to simply enter "Build2" into the "Build Artifacts Names" box.  The release already knows which artifact I am specifying as I had to choose that when I created the release.

Am I missing something?

**Comment by gregpakes** [comment]
I get this now.  Rather than specifying "Build2", I need to specify "Build2\drop".  That part was confusing to me.

**Comment by zivillian** [comment]
I've tested this and it works as expected. Thank you very much.

**Comment by chamindac** [comment]
@zivillian  Thanks for testing. @gregpakes Yes you have to specify artifactsourcealiace\artifactname as minimum path. I will update the documentation to make it more clear.
