### ISSUE TITLE
Nothing is being downloaded with TFS 2017 Update 1

### ISSUE THREAD

**Issue by reicher001** [chamindac/vsts.release.task.download-artifacts#7]
We are on the latest version of TFS and are not seeing anything downloaded.  Here is our current settings.

![image](https://cloud.githubusercontent.com/assets/23545526/24982596/c2d8ce36-1fa7-11e7-8111-5b685f6745a5.png)

**Comment by chamindac** [comment]
@reicher001  Could you post the log of the task from release management? I will setup a TFS 2017.1 and verify this.

**Comment by reicher001** [comment]
We are still using XAML builds.  Looking at this more I believe this might be contributing to this issue.  I believe this extension assumes the word 'drop' is in the path for the artifacts.  I have to assume the new build templates do that by default and the XAML builds do not.

Thoughts?

**Comment by chamindac** [comment]
I have never tested this with XAML based builds. it is not mandatory to have the word 'drop' it can be any artifact name that you provided for the artifacts in web based builds. This extension is written to be used with new web based builds and release management. I will check on the possibility of supporting XAML builds depending on if REST API supports getting details from XAML builds.

Is it OK if I close this issue and you can add a new issue saying XAML builds support is required.

**Comment by reicher001** [comment]
Yes this issue can be closed.

**Comment by chamindac** [comment]
closing and tracking with issue https://github.com/chamindac/vsts.release.task.download-artifacts/issues/8
